# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Node Script
        run: echo Hello, world!
        
      - name: Git set username
        run: git config --global user.name ${GITHUB_ACTOR}
        
      - name: Git add
        run: git add .
      
      - name: Git commit
        run: git commit -m "Add new data file."
      
      - name: Git push
        run: git push -u origin HEAD
